# SITE CONFIGURATION
title: zeinabfa # your site title
author: zeinab # You :P
description: > # Meta description of Homepage
  this is zeinab and this is for my labexam 
baseurl: "/labexam" # the subpath of your site, e.g. /blog
url: "https://zeinabfa.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'Academic Calendar', link: '/calendar'}
  - {name: 'Courses', link: '/courses'}


tagline: >
  hi its zeinab

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: fallahizeinab8317@gmail.com # email for form submission

twitter_username: zeinab1234 # replace with your_twitter_username or comment to remove link from footer
github_username:  zeinabfa # replace with your_github_username or comment to remove link from footer
instagram_username: zeinab1234 # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: zeinab # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
